{
  "type": "record",
  "name": "AccommodationEvent",
  "namespace": "pl.sadowski.sdk.avro",

  "fields": [
    {
      "name": "eventType",
      "type": {
        "type": "enum",
        "name": "AccommodationEventType",
        "symbols": [
          "ARRIVAL",
          "DEPARTURE"
        ]
      }
    },
    {
      "name": "accommodationId",
      "type": "string"
    },
    {
      "name": "reservationId",
      "type": "string"
    },
    {
      "name": "amountOfPeople",
      "type": "int"
    },
    {
      "name": "sector",
      "type": "string"
    },
    {
      "name": "accommodationType",
      "type": "string"
    },
    {
      "name": "arrivedAt",
      "type": [
        "null",
        {
          "type": "int",
          "logicalType": "date"
        }
      ],
      "default": null
    },
    {
      "name": "departedAt",
      "type": [
        "null",
        {
          "type": "int",
          "logicalType": "date"
        }
      ],
      "default": null
    },
    {
      "name": "electricityBoxNumber",
      "type": "int"
    }
  ]
}