spring:
  application:
    name: FieldService
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: field-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
      max-poll-records: 100
    listener:
      ack-mode: manual_immediate
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/dev-data
    baseline-on-migrate: true
    baseline-version: 0
server:
  port: 8082


