CREATE TABLE sector
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sector_tag      VARCHAR(255),
    max_people      INTEGER                                 NOT NULL,
    occupied_people INTEGER                                 NOT NULL,
    CONSTRAINT pk_sector PRIMARY KEY (id)
);