CREATE TABLE electricity_box
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    box_number                    INTEGER,
    free_electric_contacts_amount INTEGER                                 NOT NULL,
    positionx                     INTEGER                                 NOT NULL,
    positiony                     INTEGER                                 NOT NULL,
    sector_id                     BIGINT,
    max_capacity                  INTEGER                                 NOT NULL,
    CONSTRAINT pk_electricitybox PRIMARY KEY (id)
);

ALTER TABLE electricity_box
    ADD CONSTRAINT FK_ELECTRICITYBOX_ON_SECTOR FOREIGN KEY (sector_id) REFERENCES sector (id);