spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    location: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: 
