apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: ghcr.io/sadowskimaciej226/campsitev2/booking-service:e52ebcf1e30ba5c381df093fed432a5b77d7969c
          ports:
            - containerPort: 8080
