apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: ghcr.io/sadowskimaciej226/campsitev2/booking-service:36c87aa441740b9bf21b294ae30460734a40b600
          ports:
            - containerPort: 8080
