apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: ghcr.io/sadowskimaciej226/campsitev2/booking-service:9939549447ca13c67ec86bf30fbbb185274d20a9
          ports:
            - containerPort: 8080
