name: Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: BookingService
            image: booking-service
            path: booking-service
          - service: FieldService
            image: field-service
            path: field-service

    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u sadowskimaciej226 --password-stdin

      - name: Build image
        run: |
          docker build \
          -t ghcr.io/sadowskimaciej226/campsitev2/${{ matrix.image }}:${{ github.sha }} \
          ./${{ matrix.service }}

      - name: Push image
        run: docker push ghcr.io/sadowskimaciej226/campsitev2/${{ matrix.image }}:${{ github.sha }}

      - name: Update kubernetes manifest
        if: "!contains(github.event.head_commit.message, 'ci: update image')"
        run: |
          sed -i "s|PLACEHOLDER|${{ github.sha }}|" k8s/${{ matrix.path }}/deployment.yaml

      - name: Commit changes
        if: "!contains(github.event.head_commit.message, 'ci: update image')"
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/
          git commit -m "ci: update image to ${{ github.sha }}" || echo "No changes"
          git push