name: Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'booking-service/**'
      - 'field-service/**'
      - 'k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: BookingService
            image: booking-service
            path: booking-service
          - service: FieldService
            image: field-service
            path: field-service

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: sadowskimaciej226
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        run: |
          docker build \
            -t ghcr.io/sadowskimaciej226/campsitev2/${{ matrix.image }}:${{ github.sha }} \
            ./${{ matrix.path }}
          
          docker push ghcr.io/sadowskimaciej226/campsitev2/${{ matrix.image }}:${{ github.sha }}

  deploy-update:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, 'ci: update image')"

    steps:
      - uses: actions/checkout@v4

      - name: Update kubernetes manifests
        run: |
          sed -i "s|image: ghcr.io/.*/booking-service:.*|image: ghcr.io/sadowskimaciej226/campsitev2/booking-service:${{ github.sha }}|" k8s/booking-service/deployment.yaml
          sed -i "s|image: ghcr.io/.*/field-service:.*|image: ghcr.io/sadowskimaciej226/campsitev2/field-service:${{ github.sha }}|" k8s/field-service/deployment.yaml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/
          git commit -m "ci: update images to ${{ github.sha }}" || echo "No changes to commit"
          for i in {1..5}; do
            git pull --rebase origin main && git push && break || sleep 5
          done